image: pobj

stages:
- test

TME-9:
  script: >
    /home/pobj/run.sh -id TME-9 -name TME-9
    pobj.pinboard.document.test.ClipRectTest
    pobj.pinboard.document.test.BoardTest
    pobj.pinboard.document.test.ClipEllipseTest
    pobj.pinboard.editor.tools.test.ToolRectTest
    pobj.pinboard.editor.tools.test.ToolEllipseTest
  artifacts:
    reports:
      junit: report.xml

TME-10:
  script: >
    /home/pobj/run.sh -id TME-10 -name TME-10
    pobj.pinboard.editor.test.SelectionTest
    pobj.pinboard.editor.tools.test.ToolSelectionTest
    pobj.pinboard.editor.test.ClipboardTest
    pobj.pinboard.editor.test.ClipboardListenerTest
  artifacts:
    reports:
      junit: report.xml

TME-11:
  script: >
    /home/pobj/run.sh -id TME-11 -name TME-11
    pobj.pinboard.document.test.ClipGroupTest
    pobj.pinboard.editor.commands.test.CommandAddTest
    pobj.pinboard.editor.commands.test.CommandMoveTest
    pobj.pinboard.editor.commands.test.CommandGroupTest
    pobj.pinboard.editor.commands.test.CommandUngroupTest
    pobj.pinboard.editor.test.CommandStackTest
  artifacts:
    reports:
      junit: report.xml
